#pragma once

const char *mqttURI = "/mqtt";
const char *mqttWebsite = "<!doctype html>"
                          "<html lang=\"en\">"
                          "<head>"
                          "<meta charset=\"utf - 8\">"
                          "<title>Controller's config</title>"
                          "<style >"
                          "body {"
                          "background-color: #FAFAFA;"
                          "}"
                          "input {"
                          "width: 100%%;"
                          "}"
                          "form {"
                          "background-color: #01579B;"
                          "width: 200px;"
                          "display: block;"
                          "margin-left: auto;"
                          "margin-right: auto;"
                          "padding-left: 20px;"
                          "padding-right: 20px;"
                          "padding-top: 20px;"
                          "border: 2px solid #01579B;"
                          "border-radius: 10px;"
                          "}"
                          "p{"
                          "color: #FAFAFA;"
                          "padding: 0;"
                          "margin: 0;"
                          "}"
                          "h3, h4 {"
                          "border-bottom: 1px solid #FAFAFA;"
                          "padding-bottom: 5px;"
                          "color: #FAFAFA;"
                          "}"
                          "#btncnt{"
                          "display: flex;"
                          "justify-content: center;"
                          "align-items: center;"
                          "}"
                          "button{"
                          "width: 150px;"
                          "height: 40px;"
                          "margin-bottom: 20px;"
                          "}"
                          ".none{"
                          "margin-bottom: 20px;"
                          "padding-bottom: 20px;"
                          "}"
                          "</style>"
                          "</head>"
                          "<body>"
                          "<form action=\"/mqtt\" autocomplete=\"off\" accept-charset=\"utf-8\" method=\"post\">"
                          "<div>"
                          "<h3>MQTT config</h3>"
                          "<p>Broker IP:</p>"
                          "<input required name=\"brokerip\" value=\"%s\" maxlength=\"15\" size=\"15\" pattern=\"^((\\d{1,2}|1\\d\\d|2[0-4]\\d|25[0-5])\\.){3}(\\d{1,2}|1\\d\\d|2[0-4]\\d|25[0-5])$\"><br/><br/>"
                          "<p>Port:</p>"
                          "<input required name=\"brokerport\" value=\"%s\" type=\"text\" pattern=\"[0-9]{1,5}\" maxlength=\"5\"><br/><br/>"
                          "<p>User:</p>"
                          "<input name=\"user\" value=\"%s\" maxlength=\"32\"><br/><br/>"
                          "<p>Password:</p>"
                          "<input name=\"password\" type=\"password\" value=\"%s\" maxlength=\"32\"><br/><br/>"
                          "<p>Namespace:</p>"
                          "<input name=\"namespace\" value=\"%s\" maxlength=\"32\"><br/>"
                          "</div>"
                          "<div  class=\"none\">"
                          "</div>"
                          "<div id=\"btncnt\">"
                          "<button type=\"submit\">Apply</button>"
                          "</div>"
                          "</form>"
                          "</body>"
                          "</html>\r\n";